### ISSUE TITLE
slick is not a function

### ISSUE THREAD

**Issue by Millen31** [VladShcherbin/slickjs#2]
after I've added the package and copied the fonts and css I still get "slick is not a function". Why? 

``` javascript
$('#carousel').slick({
    });
```

btw. I'm not using the template-stuff of meteor.

**Comment by vladshcherbin** [comment]
Don't know, what causes this. The package is only a wrapper over the slick js, it just adds the slick library file to the client, so it should work everywhere on the client. You can check the [examples](https://github.com/VladShcherbin/slickjs/tree/master/examples).

And you can also make a test repo with the error.

**Comment by vladshcherbin** [comment]
Closing until the example is provided.
